apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-cronjob
  namespace: mateapp
  labels:
    app: todoapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: todoapp-cronjob
        spec:
          containers:
            - name: cron-curl
              image: busyboxplus:curl
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - curl -s http://todoapp-service.todoapp/api/health
              resources:
                requests:
                  cpu: "100m"
                  memory: "100Mi"
                limits:
                  cpu: "200m"
                  memory: "200Mi"
          restartPolicy: OnFailure
