apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todoapp
  namespace: mateapp
  labels:
    app: todoapp
spec:
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp-daemonset
          image: busyboxplus:curl
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          command:
            - /bin/sh
            - -c
            - "while true; do curl http://todoapp-service.todoapp/api/health; sleep 5; done"
